apiVersion: v1
kind: Service
metadata:
  name: mysql-internal-service
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-load-balancer-service
spec:
  type: LoadBalancer
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: mysql-cipher-credentials
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mysql-cipher-credentials
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: mysql-cipher-credentials
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mysql-cipher-credentials
          ports:
            - containerPort: 3306
              name: mysql
          livenessProbe:
            exec:
              command: [ "mysqladmin", "ping" ]
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: [ "mysqladmin", "ping" ]
            periodSeconds: 2
            timeoutSeconds: 3
          startupProbe:
            exec:
              command: [ "mysqladmin", "ping" ]
            failureThreshold: 30
            periodSeconds: 5
