apiVersion: v1
kind: Service
metadata:
  name: cvl-backend-internal-service
spec:
  ports:
    - port: 8080
  selector:
    app: cvl-backend
  clusterIP: None
---

apiVersion: v1
kind: Service
metadata:
  name: cvl-backend-load-balancer-service
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: cvl-backend
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvl-backend
  labels:
    app: cvl-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvl-backend
  template:
    metadata:
      labels:
        app: cvl-backend
    spec:
      containers:
        - name: cvl-backend
          image: cvl:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev,no-email
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-internal-service:3306/classic_virus_list?useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
            - name: SPRING_DATASOURCE_USERNAME
              value: cvl
            - name: SPRING_DATASOURCE_PASSWORD
              value: cvl
            - name: JAVA_OPTS
              value: "-Xmx2048m -Xms512m -Duser.timezone=UTC -Dfile.encoding=UTF-8"


