apiVersion: v1
kind: Service
metadata:
  name: cvl-nginx-service-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: cvl-nginx
  ports:
    - name: "80"
      # porta esterna
      port: 8000
      #porta dei pod
      targetPort: 80
