apiVersion: v1
kind: Service
metadata:
  name: mysql-internal-service
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-load-balancer-service
spec:
  type: LoadBalancer
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: G1alosai
            - name: MYSQL_DATABASE
              value: classic_virus_list
            - name: MYSQL_USER
              value: cvl
            - name: MYSQL_PASSWORD
              value: cvl
          ports:
            - containerPort: 3306
              name: mysql
          livenessProbe:
            exec:
              command: [ "mysqladmin", "ping" ]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: [ "mysqladmin", "ping" ]
            initialDelaySeconds: 45
            periodSeconds: 2
            timeoutSeconds: 1
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/mysql-data-3"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
