apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-clear-credentials
data:
  # property-like keys; each key maps to a simple value
  MYSQL_ROOT_PASSWORD: "G1alosai"
  MYSQL_DATABASE: "classic_virus_list"
  MYSQL_USER: "cvl"
  MYSQL_PASSWORD: "cvl"

  # file-like keys
#  game.properties: |
#    enemy.types=aliens,monsters
#    player.maximum-lives=5
#  user-interface.properties: |
#    color.good=purple
#    color.bad=yellow
#    allow.textmode=true
